### PR TITLE
React Native 0.81 support

### PR DESCRIPTION
**Pull request by prathameshmm02**
Add support for React Native 0.81, contains following fixes:

- Upgrade libsodium to 1.0.20 (contains 16KB alignment fix for libsodium.so)
- Enable 16KB native library alignment
- Update C++ standard to C++20 in CMakeLists.txt
- Fix an issue due to folly dep when prebuild RN deps are enabled

### CODE REVIEW

**Comment by landabaso** [comment]
Signature verification fails.
The signature file does not match [[the one distributed in the original repo](https://download.libsodium.org/libsodium/releases/libsodium-1.0.20-stable.tar.gz.minisig)]
/cc @nikgraf

**Comment by landabaso** [comment]
I’m on RN 0.79.5. This PR fixes Folly deps by adding:

```ruby
if ENV['RCT_USE_RN_DEP'] != '1'
  s.dependency 'RCT-Folly', folly_version
end
```

However, `pod install` fails with:

```
[!] Invalid `react-native-libsodium.podspec` file: undefined local variable or method `folly_version' for module Pod.
```

Suggestion: drop the variable and rely on CocoaPods resolution:

```ruby
s.dependency 'RCT-Folly'
```

This works on RN 0.79.5. Not sure about 0.80.
/cc @nikgraf

**Comment by tgreco** [comment]
> Thanks @prathameshmm02. Why not update the `.minisig` file as well? The script downloads the latest `.tar.gz`, and without the matching signature it won't be able to proceed. The `tar.gz` file has changed since your initial commit.

@prathameshmm02 whats your thoughts on this question? I think it's a valid concern

**Review by nikgraf — APPROVED** [review]
